### ISSUE TITLE
Unsupported Comp-op Color Blending Values?

### ISSUE THREAD

**Issue by csobier** [CartoDB/docs#401]
As per Steph's review of the "[Composite Operation Color Blending Values](http://docs.cartodb.com/cartodb-editor.html#composite-operation-color-blending-values)" doc.
- `Divide`, `linear-dodge` & `linear-burn` can't be used in our system. 
- [x] I will remove these from the docs for now.

- I couldn't find documentation for "clear" as a color blend mode, did u? Asking b/c it looks like alpha blend mode to me.

Will add back if these are ever supported.  @rochoa @fdansv Please advise.

**Comment by csobier** [comment]
@ztephm - Since she was the original reporter :-)

**Comment by fdansv** [comment]
To me the question is whether we are maintaining a CartoCSS reference or a CartoCSS in CartoDB reference. If our intention is to provide the community with authoritative documentation those blending modes should be included. While we're not using them in CartoDB, they're being used in Tilemill and other possible applications of Carto.

**Comment by csobier** [comment]
I believe the intention of this project was to include CartoCSS parameters that are supported with CartoDB.  This is now our internal documentation, as it applies to our product.  I hope this helps?

Also, regarding `clear` as a color blending mode, I have [another issue](https://github.com/CartoDB/docs/issues/394) about not being able to find this for Torque too.  Any ideas?

**Comment by ztephm** [comment]
hi, to clarify:

* **clear** works but we have it documented as a color composite operation instead of an alpha composite operation. Its effect looks like alpha comp-op to me but I can't tell exactly what it sh/be from this: http://www.w3.org/TR/2009/WD-SVGCompositing-20090430/#comp-op-clear

* i tested divide, linear-burn & linear-dodge in Editor only:
![screen shot 2015-10-01 at 5 03 46 pm](https://cloud.githubusercontent.com/assets/1779444/10234020/010ee9e8-6860-11e5-870c-d6e428b58161.png)

**Comment by rochoa** [comment]
The supported values are the ones found in: https://github.com/CartoDB/mapnik-reference/blob/a9a4536116aa8b3e1fe6433b2c8da25321dc7f7d/2.3.0/reference.json#L868

I have the impression we took mapnik-reference version 3.0.0 as cartocss reference and that's why we keep seeing features that don't work in cartodb because we support up to version 2.3.0.

**Comment by csobier** [comment]
- I moved "clear" to the list of alpha blending values, as per Steph.
- The other values above have already been hidden in the doc.

Otherwise, if Product supports the latest Mapnik version, we will update the doc again.  Thank you!

**Comment by ztephm** [comment]
Technically clear is both b/c it gets rid of alpha & color info, but elsewhere it's included with the alpha blending modes.
